### PR TITLE
improve setup for unix

### LINKED ISSUE #24: [Bug] remove node_modules and add .gitignore
[urgent] use a single .gitignore file for both the frontend and backend folders 

@abhinavtyagi88 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/abhinavtyagi88/tour-and-travel/blob/main/CONTRIBUTING.md) of this project.

### LINKED ISSUE #25: [Docs] [Feature] Simplify the Project Setup Process with a Build
### Category of documentation update

New addition to Project Setup guidelines.

### Describe the change you think might work

The current project setup process, which involves separate commands for the frontend and backend, could be streamlined. This documentation update will include a build script or detailed guide to simplify setting up the entire project in one go.

Proposed Improvement:
A single script or command that automates these steps:
Navigate to both the frontend and Backend directories.
Install dependencies for both.
Start both the frontend and backend servers simultaneously.
Example of a potential solution:
Create a setup.sh or setup.bat script that handles these processes:
```

#!/bin/bash
cd frontend
npm install
npm start &
cd ../Backend
npm install
npm run start
```
Alternatively, update the documentation to include instructions for setting up concurrently using tools like concurrently for Node.js. @abhinavtyagi88 

Docker might not be required at this stage.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/abhinavtyagi88/tour-and-travel/blob/main/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by vatsal-afk**
closes #25 
fixes #24 

@abhinavtyagi88 

added a setup.sh file to simply project setup for unix based systems with a single command.
Also added .gitignore so as to avoid pushing node_modules and unnecessary files to github.

setup.sh
```
#!/bin/bash
cd frontend
npm install
npm start &
cd ../Backend
npm install
npm run start
```

.gitignore
```
# Node modules for both frontend and Backend
frontend/node_modules
Backend/node_modules

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Dependency directories
node_modules/
jspm_packages/

# Build directory for frontend (React)
frontend/build/
frontend/dist/

# Temporary build files
frontend/.next/
frontend/.nuxt/

# React cache
frontend/.cache/
frontend/.eslintcache/

# Production files
frontend/.env.production
Backend/.env.production

# Local environment files
frontend/.env.local
Backend/.env.local

# Optional npm cache directory
frontend/.npm/
Backend/.npm/

# IDE specific files
.vscode/
.idea/
*.sublime-workspace

# OS generated files
.DS_Store
Thumbs.db

```

### CODE REVIEW

**Comment by vatsal-afk** [comment]
This also updates the documentation file as:
### Setup

On a UNIX system, run the following commands:

```bash
   chmod +x setup.sh
   ./setup.sh
```

**Comment by abhinavtyagi88** [comment]
will it work same as it is working on windows after merging

**Comment by vatsal-afk** [comment]
sure, you may test it by pulling the commit if you are using windows
as I have only added an alternate way of setup it wont affect the previous one

**Comment by abhinavtyagi88** [comment]
Screenshot 2024-10-19 191509

as I am seeing this i am unable to see other files in frontend and backend folder

**Comment by vatsal-afk** [comment]
image


all files are present as per my commit 
also the .gitignore must be present in the root directory and node_modules files were removed as they can be installed locally using npm install.
I don't think this might cause issue on merging.

**Comment by abhinavtyagi88** [comment]
**merged succesfully **

**Comment by abhinavtyagi88** [comment]
I have merged and now I am facing this error

Error: Cannot find module '../resource_management'

**Comment by vatsal-afk** [comment]
what was that module for? can you send me a screenshot for the same?

**Comment by abhinavtyagi88** [comment]
Screenshot 2024-10-19 233643

**Comment by vatsal-afk** [comment]
wasn't the folder name Backend instead of 'backend' also try npm install in ./Backend

**Comment by abhinavtyagi88** [comment]
Solved but I have deleted previous node_modules and package-lock.json file and reinstall them

**Pull request merged**
