### PR TITLE
Refactoring/routing

### PR DESCRIPTION
**Pull request by nadjascodejourney**
I refactored the routing to use the latest version of React Router DOM (6.4), updating the code to the new syntax. This includes also the following changes, as they came along with the refactoring of the react-router-dom version:

- Moved the navbar elements into a separate Header component for better structure and reusability.
- Implemented the layout pattern, where all pages are rendered inside the Outlet component within a new Layout component.
- Added missing pages, such as a NotFoundPage for handling 404 errors.

This update aligns the project with the latest React Router features and improves code maintainability.

### CODE REVIEW

**Comment by abhinavtyagi88** [comment]
@nadjascodejourney 
what about the previous route system that are used in app.js file

**Comment by nadjascodejourney** [comment]
> @nadjascodejourney what about the previous route system that are used in app.js file

The difference between the previous and newer version (6.4, the one, I implemented) of react-router-dom lies mainly in how routing is handled and it makes routing easier and more declarative. 
In the previous version for example, the Routes were declared directly within the JSX using Route components (like it was in App.js before). 

There were a lot of under the hood changes in the new version, here is a good article to get an overview: 

- https://dev.to/arunavamodak/react-router-v5-vs-v6-dp0

The docs have also a good overview:

- https://reactrouter.com/en/main/start/overview

As an improvement to find the route setup more easily, I would suggest the newer version. And it would probably also be more sustainable in terms of maintenance and support from react router dom to go straight to the latest version.

**Comment by abhinavtyagi88** [comment]
please Once have a look on **App.js** file and tell me that what changes I have to make on App.js file

**Comment by nadjascodejourney** [comment]
> please Once have a look on **App.js** file and tell me that what changes I have to make on App.js file

Hey, I am not quite sure what you mean with changes you would have to make here?

If you take a look at the changed files within my PR, you will already see all the necessary changes to ensure that the project runs exactly as before but only with the newest router version. 
So you don't have to change anything in App.js yourself, because I've already done that. Actually, I have only removed the router and put it in a separate file with the new spelling and the code for the navbar in a separate file called Header.js.

But if you now would rather keep the previous router version, then just dismiss my PR and everything stays the same.

**Comment by abhinavtyagi88** [comment]
you have added 6 files but you have not removed the old routes and navbar from app.js file 


Screenshot 2024-10-22 162406

Screenshot 2024-10-22 163723
Screenshot 2024-10-22 163705

**Pull request merged**
